# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be60ce736ff1aa15c6f933360d4b69ac6eca8a69e97367c43e7396c701b9ea837b9424d65c7468d141665efb52fbc29927a1e49061355be4a2488ac7f93bda49

test:
  secret_key_base: e7d834f553d917b33faf6a5b5d14291dc9402c046204449ee4d7c964a3dc0365eeaf51b80a5b5123b0aece4ccf31686d619116c88bc2c26bd51a2a9f99750e38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
